Update README
imollm/fitmeup-backend pull request #1
Opened 2022-11-16 16:04 UTC by imollm

2022-11-16 17:29 UTC, marcelowebdesigner approved these changes
muy bien!

2022-11-20 23:29 UTC, diegosaraviamamani requested changes

2022-11-20 23:29 UTC, diegosaraviamamani commented on README.md
> +- [Diego Octavio SAravia Mamani](https://github.com/diegosaraviamamani)
```suggestion
- [Diego Octavio Saravia Mamani](https://github.com/diegosaraviamamani)
```

2022-11-21 09:54 UTC, imollm commented
I think we can not wait for more time, then I'm going to merge this branch into develop just to move forward the project.

2022-11-21 09:55 UTC, merged