feat: add comments create and list endpoint, model, validator
imollm/fitmeup-backend pull request #7
Opened 2022-11-28 19:20 UTC by fjota

Se ha creado:
- El modelo comment
- Añadida la validadción
- Añadido un controlador con la lógica

2022-11-29 13:39 UTC, diegosaraviamamani approved these changes

2022-11-29 22:10 UTC, marcelowebdesigner approved these changes

2022-11-29 22:26 UTC, imollm requested changes

2022-11-29 22:26 UTC, imollm commented on src/routes/index.js
> +router.use('/comment', commentController)
```suggestion
router.use('/comment', commentRoutes)
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/validator.js
> +    comment: Joi.string().min(0).max(300).required()
Aquí deberías validar también los otros campos, `userId` y `gymId`, ya que si vienen vacíos no tiene sentido solo guardar el comentario

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +        const result = await commentDAO.getComments(gymId)
```suggestion
        const comments = await commentDAO.getComments(gymId)
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +        return result.map(data => {
```suggestion
        return comments.map(comment => {
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +                _id: data._id,
```suggestion
                _id: comment._id,
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +                comment: data.comment,
```suggestion
                comment: comment.comment,
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +                createdAt: data.createdAt,
```suggestion
                createdAt: comment.createdAt,
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +                userId: data.userId,
```suggestion
                userId: comment.userId,
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/model.js
> +                gymId: data.gymId
```suggestion
                gymId: comment.gymId
```

2022-11-29 22:26 UTC, imollm commented on src/models/comment/routes.js
> +router.post('/:gymId', middlewares.auth, commentController.create)
En términos de API Rest no tiene sentido poner un ID en una url donde el predecesor no es el modelo el cuál tiene ese ID, las peticiones `POST` toda la data se pasa por body.

Aquí te estas refiriendo al resouce `/comments` y le estas pasando por query params el ID del gimnasio.

2022-11-29 22:26 UTC, imollm commented on src/models/comment/routes.js
> +router.get('/:gymId', middlewares.auth, commentController.list)
Aquí esta pasando lo mismo estas requiriendo los comentarios del gimnasio. En términos de API Rest por buenas prácticas y convención se entiende que cuando quieres recuperar los recursos relacionados `comments` de un recurso `gym`, el endpoint debería ser `/gym/{gymId}/comments` esto se leería de la siguiente manera, "Quiero recuperar del gimnasio X sus comentarios"

2022-11-30 20:31 UTC, imollm commented
Revisa el TODO en el fichero `models/gym/model.js` linea 61

2022-11-30 21:15 UTC, fjota commented on src/models/comment/validator.js
> +    comment: Joi.string().min(0).max(300).required()
Relacionado con https://github.com/imollm/fitmeup-backend/pull/7#discussion_r1035341746 ahi si que se me fue con el gymId, el userId lo podemos obtener del mismo token no creo que sea necesario enviarlo tambien en el body.

2022-11-30 21:18 UTC, fjota commented on src/models/comment/routes.js
> +router.get('/:gymId', middlewares.auth, commentController.list)
Esto lo hice asi para tener algo con que probar que este funcionando, entiendo que esto deberia ir en el controller de gym. Una vez corriga el resto de cosas que me comentas se puede hacer una nueva tarea para añadir lo que comentas aqui.

2022-12-08 08:12 UTC, imollm commented
> Revisa el TODO en el fichero `models/gym/model.js` linea 61

Deberias revisar esto

2022-12-09 10:52 UTC, merged