Send confirmation email to admin when a user registers
imollm/fitmeup-backend pull request #8
Opened 2022-11-28 21:01 UTC by Edgar-Avila

2022-11-29 17:53 UTC, imollm commented
Debes apuntar a `develop` siempre, si te faltan cambios, debes antes de nada hacer:
- Actualizar develop: `git switch develop && git pull`
- Actualizar tu rama de develop: `git switch feat-email && git merge develop`
- Resolver conflictos si los hay
- Crear la PR apuntando a develop

2022-11-29 18:06 UTC, Edgar-Avila commented
De acuerdo, ya lo cambie a develop

2022-11-29 21:41 UTC, imollm commented on src/helpers/email.js
> +    sendMail(process.env.SUPERADMIN_EMAIL, process.env.SUPERADMIN_PASS, options);
Aqui puedes utilizar también el `config` que tenemos creado.

2022-11-29 22:00 UTC, imollm requested changes

2022-11-29 22:00 UTC, imollm commented on src/models/auth/controller.js
> +                userData.confirmationToken = await (new Jwt()).signConfirmationToken(userData);
Esta bien, pero ya que tenemos tanto el `email` y el `gymId` en el token veo innecesario guardar el token en la colección de usuario.

Lo que haría yo seria:
- No guardar el token, simplemente mandarlo por email
- Cuando el admin haga la petición al endpoint `/confimation/{token}`, hacer un decode y luego hacer una query con el `email` y el `gymId` para encontrar al usuario y poner el `isAccepted` a true.

Basicamente es para ahorrar espacio en base de datos, y no generar data extra.

2022-11-29 22:00 UTC, imollm commented on src/helpers/email.js
> +        service: "gmail",
La pregunta es si ponemos el servicio de email el email de `superadmin` debe ser estrictamente GMAIL no? Sino no enviara...

Recuerdo también que hay que activar una opción en la config de GMAIL `Less secure app access` para que apps puedan usar el servicio, y además si no recuerdo mal esto Google lo deshabilito por seguridad.

https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cif-less-secure-app-access-is-on-for-your-account

Entonces creo que esto no funcionara...

Lo has probado con un correo GMAIL?

2022-11-30 00:55 UTC, Edgar-Avila commented on src/helpers/email.js
> +    sendMail(process.env.SUPERADMIN_EMAIL, process.env.SUPERADMIN_PASS, options);
Lo saque de ahi por que en el config esta hasheado y necesitaba el texto plano para la contraseña.

2022-11-30 00:56 UTC, Edgar-Avila commented on src/models/auth/controller.js
> +                userData.confirmationToken = await (new Jwt()).signConfirmationToken(userData);
Tienes toda la razon, implementare los cambios

2022-11-30 01:02 UTC, Edgar-Avila commented on src/helpers/email.js
> +        service: "gmail",
Si lo probe, como dices necesita ese tipo de acceso. Sin embargo google provee contraseñas para aplicaciones que se pueden usar. Eso lo comente en email.js lineas 5 y 6. Pero ahora que lo mencionas me parece que lo agregare también al README.

2022-11-30 13:46 UTC, imollm commented on src/helpers/email.js
> +        service: "gmail",
Como tu quieras pero que funcione. Si tenemos que cambiar el dominio de email del superadmin a gmail lo cambiamos no pasa nada.

2022-11-30 17:34 UTC, Edgar-Avila commented on src/helpers/email.js
> +        service: "gmail",
Listo, ya hice los cambios y actualice el README

2022-11-30 19:35 UTC, imollm commented
Perfecto, ahora actualiza el doc que tenemos con el equipo de frontend https://docs.google.com/document/u/0/d/1YjSSfHhOLpUWIEMYMw2vYIab4zHd-EhQdJt3gkA3eGE/mobilebasic

2022-11-30 19:47 UTC, imollm requested changes

2022-11-30 19:47 UTC, imollm commented on src/models/auth/controller.js
> +                return res.status(404).json({
Aqui el usuario esta haciendo click a un boton, lo suyo seria mandarle una pagina html.

2022-11-30 19:47 UTC, imollm commented on src/models/auth/controller.js
> +            if(!user.isAccepted){
Aqui si le vuelve a dar al endpoint volvera a decir 200 ok, deberias poner la respuesta 200 dentro del if, y mandar otra si ya esta registrado.

Otro tip para ti, si no pones status() por defecto se establece a 200 😃.

2022-12-01 00:02 UTC, Edgar-Avila commented on src/models/auth/controller.js
> +                return res.status(404).json({
Hay alguna ruta en el front para eso ya? o lo mando a una pagina pequeña en el mismo servidor tipo
```js
return res.redirect(`/confirmation.html?email=${email}&status=${status}`)
```

2022-12-05 15:44 UTC, imollm commented on src/models/auth/controller.js
> +                return res.status(404).json({
Te funciona así? Deberías aportar pruebas (screenshoots o screen recorders)...

2022-12-05 15:48 UTC, imollm approved these changes
Lo veo más o menos bien pero me gustaría poder revisarlo también con pruebas (screenshoots o screenrecordings). En la vida real es lo suyo aportar pruebas de que el trabajo esta funcionando. Buen trabajo 🦾

2022-12-05 15:49 UTC, merged